"use client";
import {useEffect,useState} from 'react';
import {SiteLink} from './SiteLink';
import articles from '../generated/articles.json';
export function ArticleArchive({english=false}:{english?:boolean}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(1);const filtered=articles.filter(a=>(a.title+' '+(a.titleEn||'')).toLowerCase().includes(query.trim().toLowerCase()));const count=Math.ceil(filtered.length/12);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),q=params.get('q')||params.get('s')||'';const total=articles.filter(a=>(a.title+' '+(a.titleEn||'')).toLowerCase().includes(q.trim().toLowerCase())).length;setQuery(q);setPage(Math.min(Math.max(1,Number(params.get('page'))||1),Math.max(1,Math.ceil(total/12))))},[]);
 return <section className="article-archive" lang={english?'en':'th'}><p className="eyebrow">AITSCCTV</p><h1>{english?'Articles & project stories':'บทความและผลงานของ AITSCCTV'}</h1><p>{english?'Explore our complete collection. Original articles are available in Thai.':'รวมบทความ ความรู้ และตัวอย่างผลงานทั้งหมด แยกจากหน้าแรกเพื่อให้เลือกอ่านได้สะดวก'}</p><SiteLink prefetch={false} className="archive-portfolio-link" href="/our-standard/">{english?"View project portfolio (Thai) →":"ดูผลงานที่ผ่านมา →"}</SiteLink><label className="archive-search">{english?'Search articles':'ค้นหาบทความ'}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={english?'CCTV, smart home, network…':'กล้องวงจรปิด, Smart Home, Network…'}/></label><p role="status">{english?`${filtered.length} articles`:`${filtered.length} บทความ`}</p><div className="archive-grid">{filtered.slice((page-1)*12,page*12).map((a,index)=><article key={a.href}>{a.image&&<a href={a.href} aria-label={english?(a.titleEn||a.title):a.title}><img src={a.image} srcSet={a.srcSet||undefined} sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1024px) 45vw, 370px" width={a.width} height={a.height} alt="" loading={index===0?"eager":"lazy"} fetchPriority={index===0?"high":undefined} decoding="async"/></a>}<div><h2><a href={a.href} lang={english&&!a.titleEn?'th':undefined}>{english?(a.titleEn||a.title):a.title}</a></h2><a href={a.href}>{english?'Read original article (Thai) →':'อ่านบทความ →'}</a></div></article>)}</div>{!filtered.length&&<p>{english?'No matching articles. Try another search.':'ไม่พบบทความ ลองค้นหาด้วยคำอื่น'}</p>}{count>1&&<nav className="archive-pagination" aria-label={english?'Article pages':'หน้าบทความ'}><button disabled={page===1} onClick={()=>{setPage(page-1);document.querySelector('.archive-grid')?.scrollIntoView()}}>{english?'Previous':'ก่อนหน้า'}</button><span>{page} / {count}</span><button disabled={page>=count} onClick={()=>{setPage(page+1);document.querySelector('.archive-grid')?.scrollIntoView()}}>{english?'Next':'ถัดไป'}</button></nav>}</section>
}
