"use client";
import {useEffect,useState} from 'react';
import {SiteLink} from './SiteLink';
import articles from '../generated/articles.json';
import englishEditorial from '../generated/english-editorial-index.json';
import {localePath} from '../lib/locale-path';
export function ArticleArchive({english=false}:{english?:boolean}){
 const englishArticle=(href:string)=>englishEditorial.find(article=>article.original===href);
 const matches=(article:typeof articles[number],value:string)=>(english?(englishArticle(article.href)?.title||article.titleEn||article.title):article.title).toLowerCase().includes(value.trim().toLowerCase());
 const [query,setQuery]=useState(''),[page,setPage]=useState(1);const filtered=articles.filter(a=>matches(a,query));const count=Math.ceil(filtered.length/12);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),q=params.get('q')||params.get('s')||'';const total=articles.filter(a=>matches(a,q)).length;setQuery(q);setPage(Math.min(Math.max(1,Number(params.get('page'))||1),Math.max(1,Math.ceil(total/12))))},[english]);
 return <section className="article-archive" lang={english?'en':'th'}><p className="eyebrow">AITSCCTV</p><h1>{english?'Articles & project stories':'บทความและผลงานของ AITSCCTV'}</h1><p>{english?'Explore our articles, technical insights and installation project stories.':'รวมบทความ ความรู้ และตัวอย่างผลงานทั้งหมด แยกจากหน้าแรกเพื่อให้เลือกอ่านได้สะดวก'}</p><SiteLink prefetch={false} className="archive-portfolio-link" href={localePath("/our-standard/",english)}>{english?"View project portfolio →":"ดูผลงานที่ผ่านมา →"}</SiteLink><label className="archive-search">{english?'Search articles':'ค้นหาบทความ'}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={english?'CCTV, smart home, network…':'กล้องวงจรปิด, Smart Home, Network…'}/></label><p role="status">{english?`${filtered.length} articles`:`${filtered.length} บทความ`}</p><div className="archive-grid">{filtered.slice((page-1)*12,page*12).map((a,index)=><article key={a.href}>{a.image&&<SiteLink prefetch={false} href={english?(englishArticle(a.href)?.href||a.href):a.href} aria-label={english?(englishArticle(a.href)?.title||a.titleEn||a.title):a.title}><img src={a.image} srcSet={a.srcSet||undefined} sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1024px) 45vw, 370px" width={a.width} height={a.height} alt="" loading={index===0?"eager":"lazy"} fetchPriority={index===0?"high":undefined} decoding="async"/></SiteLink>}<div><h2><SiteLink prefetch={false} href={english?(englishArticle(a.href)?.href||a.href):a.href} >{english?(englishArticle(a.href)?.title||a.titleEn||a.title):a.title}</SiteLink></h2><SiteLink prefetch={false} href={english?(englishArticle(a.href)?.href||a.href):a.href}>{english?'Read article →':'อ่านบทความ →'}</SiteLink></div></article>)}</div>{!filtered.length&&<p>{english?'No matching articles. Try another search.':'ไม่พบบทความ ลองค้นหาด้วยคำอื่น'}</p>}{count>1&&<nav className="archive-pagination" aria-label={english?'Article pages':'หน้าบทความ'}><button disabled={page===1} onClick={()=>{setPage(page-1);document.querySelector('.archive-grid')?.scrollIntoView()}}>{english?'Previous':'ก่อนหน้า'}</button><span>{page} / {count}</span><button disabled={page>=count} onClick={()=>{setPage(page+1);document.querySelector('.archive-grid')?.scrollIntoView()}}>{english?'Next':'ถัดไป'}</button></nav>}</section>
}
