"use client";
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import translations from '../lib/home-en.json';
import {SiteLink} from './SiteLink';
import {services,navGroups} from '../lib/navigation';
export function Header({logo}:{logo:string}){
 const [open,setOpen]=useState(false);const pathname=usePathname(),en=pathname.startsWith('/en');useEffect(()=>{document.documentElement.lang=en?'en':'th'},[en]);const t=(text:string)=>(en?({...translations,'หน้าแรก':'Home','บริการของเรา':'Services','ผลงานของเรา':'Our work','ผลงานที่ผ่านมา':'Project portfolio','วีดีโอ':'Videos','เกี่ยวกับเรา':'About us','ร่วมงานกับเรา':'Careers','ติดต่อเรา':'Contact','เข้าสู่ระบบช่าง':'Technician login'} as Record<string,string>)[text]||text:text);const localizedRows=(rows:readonly (readonly [string,string])[])=>rows.map(([text,url])=>[t(text)+(en?' (TH)':''),url] as const);
 return <><a className="skip" href="#main">{en?"Skip to content":"ข้ามไปยังเนื้อหา"}</a><header className="site-header"><div className="header-inner"><SiteLink href={en?"/en/":"/"} aria-label={en?"AITSCCTV home":"AITSCCTV หน้าแรก"}><img className="logo" src={logo} width={106} height={53} alt="AITSCCTV" /></SiteLink><button type="button" className="menu-toggle cursor-pointer" aria-expanded={open} aria-controls="navigation" aria-label={en?(open?'Close menu':'Open menu'):(open?'ปิดเมนู':'เปิดเมนู')} onClick={()=>setOpen(!open)}>☰</button><nav id="navigation" aria-label={en?"Main navigation":"เมนูหลัก"} className={open?'open':''} onClick={e=>{if((e.target as HTMLElement).closest('a')){setOpen(false);e.currentTarget.querySelectorAll('details').forEach(d=>d.open=false)}}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);e.currentTarget.querySelectorAll('details').forEach(d=>d.open=false)}}}><SiteLink href={en?"/en/":"/"}>{t("หน้าแรก")}</SiteLink><Dropdown title={t("บริการของเรา")} rows={localizedRows(services)}/><SiteLink href={en?"/en/articles/":"/articles/"}>{en?"Articles":"บทความ"}</SiteLink>{navGroups.map(g=><Dropdown key={g.title} title={t(g.title)} rows={localizedRows(g.rows)}/>)}<div className="language-switch" aria-label="Language"><SiteLink href={pathname==="/en/articles/"?"/articles/":"/"} aria-current={!en?"page":undefined}>TH</SiteLink><span>/</span><SiteLink href={pathname==="/articles/"?"/en/articles/":"/en/"} aria-current={en?"page":undefined}>EN</SiteLink></div></nav><a className="header-line" href="https://lin.ee/ZianhmV"><span aria-hidden="true">LINE</span> {en?"Chat with us":"คลิกเพิ่มเพื่อนมาคุยกัน"}</a></div></header></>;
}
function Dropdown({title,rows}:{title:string;rows:readonly (readonly [string,string])[]}){return <details className="nav-group" onMouseEnter={e=>{if(matchMedia('(min-width:1025px) and (hover:hover)').matches)e.currentTarget.open=true}} onMouseLeave={e=>{if(matchMedia('(min-width:1025px) and (hover:hover)').matches&&!e.currentTarget.contains(document.activeElement))e.currentTarget.open=false}}><summary>{title}</summary><div className="nav-sub">{rows.map(([text,url])=><SiteLink key={url} href={url}>{text}</SiteLink>)}</div></details>}
