import content from '../generated/service-content.json';
import gallery from '../generated/team-gallery.json';
import {SiteLink} from './SiteLink';
import {translateText,translateData} from '../lib/localization';
import {localePath} from '../lib/locale-path';
import editorialLinks from '../generated/editorial-links.json';
type Locale={english?:boolean};

type Image={image?:string;srcSet?:string;width?:number;height?:number};
type Project=Image&{title:string;href:string;kind:string};
type Service={label:string;points:string[];context:string;projects:Project[];warranties:string[];hasPublishedPrices:boolean};
const service=(path:string,english=false)=>english?translateData((content as Record<string,Service>)[path]):(content as Record<string,Service>)[path];
const quotation='https://docs.google.com/forms/d/e/1FAIpQLSdB3VqQ5hoTTrXIbbitcY-3NUoRikdHlloTxfnEPzHm-r15kA/viewform';
const stages=[['overview',"ภาพรวมบริการ"],['benefits',"ประโยชน์"],['options',"รูปแบบและราคา"],['projects',"ผลงานที่เกี่ยวข้อง"],['contact',"ติดต่อทีมงาน"]] as const;

export function ServiceContents({english=false}:Locale={}){return <nav className="service-contents" aria-label={translateText("หัวข้อบริการ",english)}>{stages.map(([id,label])=><a key={id} href={'#service-'+id}>{translateText(label,english)}</a>)}</nav>}
export function ServiceTrust({english=false}:Locale={}){return <aside className="service-trust"><p>{translateText("AITSCCTV ออกแบบและติดตั้งโดยทีมงานมืออาชีพ พร้อมดูแลหลังส่งมอบงาน",english)}</p><SiteLink prefetch={false} href={localePath("/about-us/#our-team",english)}>{translateText("รู้จักทีมงานของเรา →",english)}</SiteLink></aside>}
export function ServiceBenefits({path,english=false}:{path:string}&Locale){return <ul className="service-benefit-list">{service(path,english).points.map(point=><li key={point}>{point}</li>)}</ul>}
export function ServicePricing({path,english=false}:{path:string}&Locale){const data=service(path,english);return <p className="service-pricing-note">{data.hasPublishedPrices?translateText("กรุณายืนยันราคา อุปกรณ์ และเงื่อนไขกับทีมงานก่อนตัดสินใจ",english):translateText("ค่าบริการประเมินตามพื้นที่ อุปกรณ์ และขอบเขตงาน ติดต่อทีมงานเพื่อขอใบเสนอราคา",english)} <a href="#service-contact">{translateText("ขอใบเสนอราคา →",english)}</a></p>}
export function ServiceWarranty({path,english=false}:{path:string}&Locale){const data=service(path,english);return data.warranties.length?<aside className="service-warranty"><h3>{translateText("การรับประกันของบริการนี้",english)}</h3>{data.warranties.map(text=><p key={text}>{text}</p>)}<a href="#service-contact">{translateText("สอบถามเงื่อนไขการรับประกันเพิ่มเติม →",english)}</a></aside>:null}
export function ServiceProjects({path,english=false}:{path:string}&Locale){
 const data=service(path,english);const hrefFor=(href:string)=>english?((editorialLinks as Record<string,string>)[href]||href):href;
 return <div className="service-projects">{data.context&&<p className="service-project-context">{data.context}</p>}{data.projects.length?<div className="service-project-grid">{data.projects.map(project=><article key={project.href} className="service-project-card">{project.image&&<SiteLink prefetch={false} href={hrefFor(project.href)} tabIndex={-1} aria-hidden="true"><img src={project.image} srcSet={project.srcSet} sizes="(max-width: 640px) calc(100vw - 40px), (max-width: 1024px) 45vw, 370px" width={project.width} height={project.height} alt="" loading="lazy" decoding="async"/></SiteLink>}<div><p className="service-project-type">{project.kind==='project'?translateText("ผลงานที่เกี่ยวข้อง",english):translateText("บทความที่เกี่ยวข้อง",english)}</p><h3><SiteLink prefetch={false} href={hrefFor(project.href)}>{project.title}</SiteLink></h3><SiteLink prefetch={false} className="service-project-read" href={hrefFor(project.href)}>{translateText("อ่านรายละเอียด →",english)}</SiteLink></div></article>)}</div>:<div className="service-project-request"><p>{english?`Looking for ${data.label} project examples suited to your property?`:<>ต้องการดูตัวอย่างงาน{data.label}ที่เหมาะกับพื้นที่ของคุณ?</>}</p><p>{translateText("ติดต่อทีมงานเพื่อสอบถามตัวอย่างงานและแนวทางออกแบบ",english)}</p><a href="#service-contact">{translateText("สอบถามตัวอย่างงาน →",english)}</a></div>}<SiteLink prefetch={false} className="service-portfolio-link" href={localePath("/our-standard/",english)}>{translateText("ดูผลงานที่ผ่านมา →",english)}</SiteLink></div>;
}
export function ServiceContact({path,english=false}:{path:string}&Locale){return <div className="service-contact"><h3>{english?`Discuss ${service(path,english).label}`:<>ปรึกษาเรื่อง{service(path,english).label}</>}</h3><p>{translateText("แจ้งพื้นที่ใช้งาน ความต้องการ และงบประมาณ เพื่อให้ทีมงานช่วยประเมินขอบเขตงาน",english)}</p><div className="service-contact-actions"><a className="service-quote" href={quotation} target="_blank" rel="noopener">{translateText("ขอใบเสนอราคา",english)}</a><a className="service-line" href="https://lin.ee/ZianhmV" target="_blank" rel="noopener">{translateText("คุยผ่าน LINE",english)}</a><a className="service-call" href="tel:0944606196">{translateText("โทร 094 460 6196",english)}</a></div><a href="mailto:info@aitscctv.com">info@aitscctv.com</a></div>}
export function AboutTeamGallery({english=false}:Locale={}){
 const images=(items:typeof gallery)=><div className="about-team-grid">{items.map((item,i)=><a href={item.original} key={item.original} target="_blank" rel="noopener" aria-label={translateText("เปิดภาพงานติดตั้ง ",english)+(translateText(item.alt,english)||String(i+1))}><img src={item.image} srcSet={item.srcSet} sizes="(max-width: 640px) 42vw, (max-width: 1024px) 28vw, 270px" width={item.width} height={item.height} alt={/[\u0e00-\u0e7f]/.test(item.alt)?translateText(item.alt,english):translateText("ภาพงานติดตั้งและมาตรฐานการทำงานของ AITSCCTV",english)} loading="lazy" decoding="async"/></a>)}</div>;
 return <section id="our-team" className="about-team"><p className="eyebrow">OUR TEAM</p><h2>{translateText("ทีมงานของเรา AITSCCTV",english)}</h2><p>{translateText("พวกเรา AITSCCTV พร้อมสร้างมาตรฐานความปลอดภัยใหม่ให้คุณ",english)}</p>{images(gallery.slice(0,8))}<details className="about-team-more"><summary>{english?`View more installation photos (${gallery.length-8})`:<>ดูภาพงานติดตั้งเพิ่มเติม ({gallery.length-8} ภาพ)</>}</summary>{images(gallery.slice(8))}</details></section>;
}
